### PR TITLE
Add Date-Slider to graphs, replacing '2-weeks' toggle

### PR DESCRIPTION
**Pull request by tumbleshack**
Addresses #86

### CODE REVIEW

**Comment by xunhuang** [comment]
amazing! checking right now.

**Comment by xunhuang** [comment]
Functionally it works great! thank you!
 here are some suggestion for improvement: 
1) Can we make the control smaller? Stylistically we want to keep the site minimal. Desktop version is definitely too wide. Also maybe change the label to "Dates"

2) interaction wise, can we make it such that it changes the date as you slide, and not have to release the mouse? 

Lastly, thank you for proactively looking at all the graphs and changing all of them. that's amazing.

**Comment by xunhuang** [comment]
also saw that you added the linear vs log thing. maybe better to do something like this? 

with the Toggle Group buttons thing. 

image

**Comment by tumbleshack** [comment]
> Functionally it works great! thank you!
> here are some suggestion for improvement:
> 
> 1. Can we make the control smaller? Stylistically we want to keep the site minimal. Desktop version is definitely too wide. Also maybe change the label to "Dates"
> 2. interaction wise, can we make it such that it changes the date as you slide, and not have to release the mouse?
> 
> Lastly, thank you for proactively looking at all the graphs and changing all of them. that's amazing.

Happy to help!

I can certainly make those changes if you prefer. I made those style and function decisions because:
1. As time passes on, we'll have more and more days to choose from; with a small slider, it could quickly become difficult for users to select dates with accurate granularity.
2. Re-rendering the graph seems expensive; for users with a slow connection or slow mobile devices, re-rendering as they slide could drastically increase lag (or the perception thereof). 

Let me know!

**Comment by tumbleshack** [comment]
> also saw that you added the linear vs log thing. maybe better to do something like this?
> 
> with the Toggle Group buttons thing.

Yes, I can do that! This style looks much better.

A couple of other related inquiries: I noticed some graphs have a "show all dates" toggle. Should I replace those with the slider as well? The `GraphNewCases` stores the user state (now including slider position) as a Cookie, while the other graphs do not. Should saving the user state be added?

If yes, should these changes be in a new PR?

**Comment by xunhuang** [comment]
- For this set of graphs I don't think people care to be super precise about the date range. So coarse grain control works. 
- All the data for the graph is already in the client, so there is no additional data fetching cost. there is rendering cost, but I think people actually enjoy sliding the dates back and forth and watch lines move. 

Lastly, I also want the slider on the Maps too. for that I agree precision matters much more, so I would go for larger slider, and will need to think about the data fetch part as well: https://covid19.cheme.cornell.edu/

**Comment by xunhuang** [comment]
> A couple of other related inquiries:
> 
> 1. I noticed some graphs have a "show all dates" toggle. Should I replace those with the slider as well?
> 2. The `GraphNewCases` stores the user state (now including slider position) as a Cookie, while the other graphs do not. Should saving the user state be added?
> 
> If yes, should these changes be in a new PR?

I think we should do both of these. for 2) I hestitated a bit, I think the value is that when user compare? by navigating from County -> metro -> state -> country, staying at the same date range helps them compare apples-to-apples.  That said, if we get negative feedback from users. We can change that later. 

Yes, new PR is better, so easier to review, accept and rollback if something is wrong.

**Comment by tumbleshack** [comment]
@xunhuang , made the style and functional changes to the slider. How does it look now?

With regard to the other changes, I think I'll break them up like this. A new issue and PR for:
1. A reusable `useStickyState` hook, adds cookies to `useState`
2. Replacing the ant switch with a toggle button
3. Adding a slider to the map

Thoughts?

**Comment by xunhuang** [comment]
these are perfect! thank you so much for your help in this project. Don't you have school work to do? :)

**Pull request merged**
