### PR TITLE
Move graph options to a drop-down menu

### PR DESCRIPTION
**Pull request by lym953**
image

And I reordered the options by putting at the front what I think are more commonly used.
- Total
- New
- Death
- 2 Weeks
- Log
Feel free to reorder them if you think differently.

### CODE REVIEW

**Comment by xunhuang** [comment]
Please leave the original two buttons at their old place.  have the drop down aligned to the right. Also want to have the option of not showing the results selected there (since they will see the lines already.) 

want to keep the GUI clean and unclutterred. thank you!

**Comment by xunhuang** [comment]
can you also please result the conflict? thanks!

**Comment by lym953** [comment]
Update:
- leave the original two buttons at their old place
- have the drop down aligned to the right
- do not show which options are selected
- resolve rebase conflicts

**Comment by xunhuang** [comment]
awesome!

**Pull request merged**
