### PR TITLE
Create an SVG map component

### PR DESCRIPTION
**Pull request by aschleck**
It supports pinch zoom and pan that renders from a given SVG file and fills in colors based on props passed in. Additionally, includes a pin component to display data where the user clicks. This is super messy and not really ready for users, but I think it's good enough that someone could do something with.

I probably shouldn't spend more time on this feature since it's been interfering with my sleep schedule pretty badly, my hope is that if someone does some small tweaks (adjusting the pin text inside getPinText_ and changing the coloring in InfectionMap#componentDidMount) it would be good enough for someone to try throwing in a page. For now, added a simple route for testing. What do you think?

I have NOT tested this on mobile, but have tested on Chrome and Firefox.

### CODE REVIEW

**Comment by aschleck** [comment]
One thing I forgot to mention: if we do plop this into a public place we should credit https://commons.wikimedia.org/wiki/File:USA_Counties_with_FIPS_and_names_including_territories.svg somewhere

**Comment by xunhuang** [comment]
Thank you April for your hard work! I’ll take a look at this and see how to
leverage it. This project is volunteer work, we all have day jobs. Please
take care of yourself, pace yourself. this is the time that we need to
treat our immune system well, not a great time to get sick. Thanks ahead
and appreciate your tremendous effort.

**Comment by aschleck** [comment]
I know I know!

Anyway I tested it this morning on my Android phone and fixed some things. Safari on my Mac has a pinch zoom feature I can't seem to stop, which breaks stuff, and I don't have an iPhone test with.

**Comment by xunhuang** [comment]
looks safe to add. will merge. but will surface the feature a little later. sounds ok?

Again, thanks for the amazing hardwork!

**Pull request merged**
