### PR TITLE
Trending Line and Day to Double

### PR DESCRIPTION
**Pull request by shihangw**
Used https://simplestatistics.org/docs/ to calculate linear regression

Demos
Screen Shot 2020-03-31 at 11 20 11 AM

Screen Shot 2020-03-31 at 12 35 13 AM
Screen Shot 2020-03-31 at 12 35 30 AM
Screen Shot 2020-03-31 at 12 35 36 AM
Screen Shot 2020-03-31 at 12 35 43 AM
Screen Shot 2020-03-31 at 12 35 51 AM
Screen Shot 2020-03-31 at 12 36 01 AM

**if there are too few data, then we won't show it**

Screen Shot 2020-03-31 at 12 54 52 AM

### CODE REVIEW

**Comment by lym953** [comment]
This is cool! Will the trending line be hidden if "total" line is hidden?

**Comment by shihangw** [comment]
yes

**Comment by lym953** [comment]
Could you squash the commits into one? Too many commits may make commit history messy.

**Comment by shihangw** [comment]
@lym953 we should enforce using "squash and merge" option and let github squash for us..

**Comment by xunhuang** [comment]
option changed. it this ready to go?

**Comment by shihangw** [comment]
yes it works on my side.

**Comment by xunhuang** [comment]
got it! will do it now.

**Pull request merged**
