### PR TITLE
Support hiding any of the three lines

### PR DESCRIPTION
**Pull request by lym953**
image

Thus it's easier to see the trend of new cases and deaths.

### CODE REVIEW

**Comment by lym953** [comment]
Note: Legends are not controlled by these switches. But I don't think it's high priority to support that.
image

**Comment by xunhuang** [comment]
hey, how does it look on mobile? can you shrink the text, make them less verbose, but find a way to fit into one line? eg. Log Scale -> Log, Last 2 weeks --> 2 Weeks. New cases -> New.

**Comment by xunhuang** [comment]
Please test on the "mobile view" with chrome. Make sure it fits into iphone XS. why? because that's what I use. :)

**Comment by lym953** [comment]
@xunhuang Good point! And do you know how to force two Grids (the toggle switch and the text) to be on the same row? The screenshot below doesn't look very good. I spent some time but did not find an answer.
image

**Comment by lym953** [comment]
Update: made labels shorter.

**Pull request merged**
