### PR TITLE
Replace Day2x with growth rate in main chart

### PR DESCRIPTION
**Pull request by shihangw**
Since cases will take a long time to double, switching trending to growth rate will better describe situation.

Verify the math with US total case:

4/10: 508297 (+7.61%)
4/9: 472331 (+8%)
4/8: 437358 (+8.16%)
4/7: 404333

Screen Shot 2020-04-12 at 2 07 59 PM

### CODE REVIEW

**Comment by xunhuang** [comment]
actually, can we try how having both looks like? People really like the doubling metric. Maybe one on top of another? maybe color it grey so it's more subtle?

**Comment by shihangw** [comment]
How about this

**Comment by shihangw** [comment]
How about this

Screen Shot 2020-04-12 at 2 27 05 PM

**Comment by xunhuang** [comment]
reverse it,  9 days to double (+8% daily)?

**Comment by shihangw** [comment]
This feels better

Screen Shot 2020-04-12 at 2 39 11 PM

**Comment by shihangw** [comment]
I don't know how to make text grey. I thought I could use custom renderer using "content" property but the custom label isn't showing up. Will pause on this since it's not as important as data  https://recharts.org/en-US/api/Label#content

**Comment by xunhuang** [comment]
Thanks. I’ll take care of the rest. :)

Shawn W <notifications@github.com>於 2020年4月12日 週日，下午2:44寫道：

**Pull request merged**
