### PR TITLE
An independent page for ROW data to play around with

### PR DESCRIPTION
**Pull request by aschleck**
Okay so I didn't bring in any of the styling, the tables aren't sortable, I dropped the standard header because I didn't want to spend time making it work, I didn't add a log toggle, a few other shortcuts, and here we are.

A nice example page: http://localhost:3000/country/US/s/California

image

I decided to go with an ECS data model since I am pretty fired up about ECS currently, which I think is good in the longer run anyway. It seems like we're going to have all sorts of patchwork data, some places have recovery, some don't, some have hospitalization data, some don't, some will have Rt, some may not. With components, we can add functionality to the page to check if the data is available and render if it is, or hide it if not.

This model currently assumes that everything is loaded into the world object at page load, but I think extending it to allow fetching promises is super feasible. I just hope we don't hack that up since it has the potential to be gnarly.

What do you think?

### CODE REVIEW

**Comment by aschleck** [comment]
I should acknowledge that the numbers in the graph seem different than the numbers shown on the main page, I probably did something wrong.

I already caught that the numbers in the table in that screenshot are fubar, and fixed that.

**Comment by xunhuang** [comment]
Frankly this is amazing. It is astonishing how beautiful the code is and could do so much. Admittedly I will have to digest it a little more to understand how things are wired together. Also, also to mention how cool it is to just navigate through the namespaces from data model and not have to force fit back to the "fips" model - that's really where most of the shit from normalized.js comes from.

question: what's the ECS data model? I don't really see that mentioned in the code.

**Comment by aschleck** [comment]
I'm super glad you like it! It's definitely a little different, but I think it makes sense. I just pushed something for trend lines and log scales.

ECS is this: https://en.wikipedia.org/wiki/Entity_component_system . Though really this is EC, since we don't ever change the data so there's no point in having systems. Basically rather than having one object and inheritance, like UnitedStates.js, we instead of some central IDs and then link those simple component objects to those IDs. So the basic data needed for rendering might be a component, and hospitalization might be a component, and the map parameters might be a component. So that way we if we have the map component then we show the map, and if we don't then we don't.

**Comment by aschleck** [comment]
I made it significantly faster, but one thing that is happening is that I am guessing the last item of the tables (eg confirmed, active, deaths) is the most recent data point. And it's often not, for example in the US the last date in the last for confirmed is 03/15/2020. Can we sort the lists by date when generating them?

It'd also probably make the frontend faster to just use unix timestamps in those lists, but I think I got the cost low enough that it doesn't matter.

**Comment by aschleck** [comment]
image

(Also note the pesky "Chicago" showing up for no reason in that table ☹️)

**Comment by aschleck** [comment]
I don't think I should keep working on this without more feedback, but anyway I was playing around with a different UX look. I feel like the current UX is a bit of a dead end since it just gets harder and hard to shove stuff places. I think with this proposal we could have a hamburger menu (the three horizontal lines that open up a slide in menu in MUI), and have space for linking to different parts of the site (probably not very useful unless you decide to pursue some random data like you suggested re FluLab.)

image

**Comment by xunhuang** [comment]
Hi April, sorry for being quiet today. Too much going on at home front with the kids not occupied with their school zoom sessions. 

I saw that you put in lots of work in creating some of graphs and making them a lot cleaners. I think we need to settle on the "what" first. 

1) While the new navigation structure looks clean, three things seems we don't have a good solution yet:
a) the structure inherits from the data hierarchy from the worlddata.json file. This works well with ROW, but for US, we do have the metro concept that needs to be injected into hierarchy, and some don't neatly fit into the states construct. (actually same as current UX too.)  
b) if we have (county, metro, state, country, earth), we are have 5 tabs that will be impossible to fit in one line 
c) It seems easy to get stuck in a leave node, for example, if you get to Yemen, it's hard to get to other countries unless you scroll down to the country list in the bottom. This is also true in current UI when selecting states. 

2) it will take some time to fit the US data with all data juggling into the world model. Maybe it would be best for us to launch a common navigation structure, but when it goes into US, it shows US data/subcomponents as is. 

3) what to do with the Map, Tests, Hospitalization? for the ROW we don't have test/hospitalization yet, but we do need to figure out the Maps. 

4.) On the graphs, should we add all the lines into one graphs and let people choose to their hearts content, or should we break into different graphs. The former is cleaner, but it does introduce issues with laying the burden on the user, and some lines need to be different scales (left vs. right axis, some people want to see 3-d average etc). we might be are solving too many problems at one go.

**Comment by xunhuang** [comment]
How about this for bridging between US and the Rest of the world? 

image

When clicked on the new world, go to your new pages, when clicked on the US, goes to the old page /US?

To launch, we need 
1) Data generation automated and cleaned up.  P0
2) this bridging code   -P0 
3) geoIP --> country  P1 for launch, P0 (before we run Ads for traffic generation) 
4) Search bar for Rest of the world - P2

what do you think? After that we can refine what the end state for ROW would look like, and whether we want to ditch the US part entirely.

**Comment by aschleck** [comment]
> I saw that you put in lots of work in creating some of graphs and making them a lot cleaners. I think we need to settle on the "what" first.

Definitely agree, I knew there was a risk of total rejection here but at least wanted to explore a few directions.
 
> 1. While the new navigation structure looks clean, three things seems we don't have a good solution yet:
>    a) the structure inherits from the data hierarchy from the worlddata.json file. This works well with ROW, but for US, we do have the metro concept that needs to be injected into hierarchy, and some don't neatly fit into the states construct. (actually same as current UX too.)

Just to make sure I understand the current metro situation: we currently copy a metro into every state it intersects. So we have two identical "Kansas City" metros, with the only difference being the state they're parented up to. This has the downside of being annoying and whacky, but the upside of making the top nav work when going into a county under that metro. In terms of the UX, it kind of almost makes sense, but is a tiny bit weird since jumping around counties will keep you in the same metro but randomly switch your state.

I did think a bit about metros, but mostly was thinking in terms of keeping the current UX. Thinking about it more, I came up with the following suggestion. But my suggestion has five bullet points, which is probably a bad sign.

* make metro entities under the country that contains them. Place the numerical data as a component, a list of all the counties it contains as a component, and a list of the states it intersects as a component
* When viewing an entity that has a list of intersecting states (ie a metro) and is in at least two states, don't show a state in the hierarchy. Instead, have some message below like "Part of <link>Kansas</link> and <link>Missouri</link>" without any numbers
* For the state page, we can link to the metros it contains via the ChildrenComponent I already added. The UX here might be a little funky, you go from a state page to a metro it contains but on the metro page we don't highlight the state you just came from (instead it would just be shown in that message in the previous bullet)
* When selecting a county, I don't know what to really do. Certainly we could make it work like in the current UX, though it'd be similar to the current approach (at least we wouldn't duplicate the data I guess?) My best thought, and this might be more from an engineer perspective than a UX perspective, would be to add a component linking to the metro for every county in a metro. Then, we could show a message like "Part of the <link>Bay Area</link>" and not surface the metro in the hierarchy.
* If we just decided to never show state numbers on the metro page then it would mean the display for a metro's intersecting states and the display for a county's metro are the same. Which would be cool because they could both use the same GroupComponent or whatever and use the same code to render. But I think that might be giving up too much.

In summary, I have no idea :(

>    b) if we have (county, metro, state, country, earth), we are have 5 tabs that will be impossible to fit in one line

Yeah I personally have given up on making it fit on one line, it just seems really restrictive. I was trying to think of some options for making a multiline version look okay, I came up with this but can't decide how good or bad it is.

image

>    c) It seems easy to get stuck in a leave node, for example, if you get to Yemen, it's hard to get to other countries unless you scroll down to the country list in the bottom. This is also true in current UI when selecting states.

That's definitely true, though I am not sure how users really want to navigate there. We could definitely do something like go up the hierarchy until we find a node with multiple children, and then display that table on the Yemen page. So like you're on Yemen and it says "Other Countries". I guess this is similar to how you did "Nearby counties" which I think was a good save, but for the case where we have no data.

> 2. it will take some time to fit the US data with all data juggling into the world model. Maybe it would be best for us to launch a common navigation structure, but when it goes into US, it shows US data/subcomponents as is.

I forgot to write this but yes I was thinking this as well.

> 3. what to do with the Map, Tests, Hospitalization? for the ROW we don't have test/hospitalization yet, but we do need to figure out the Maps.

Do you mean in terms of code for these or in terms of data?

Test/hospitalization should fit under the component model easily, and we can just intelligently turn those graphs on and off depending on the data's presence. How to make fetching components that might need to be async loaded work is something that I know is possible, but haven't actually put any work towards.

I guess my first thought for maps is, do we really need it? My second thought for maps is that in the worst case (at least for the code) we just take countyMapConfig and make it a component and call it a day. As far as data, I was assuming there are world JSON files but I have no idea how performant RSM would be with them. I have had some problems with RSM on the US map on my phone, maybe I just did something wrong though. We could also throw in the towel on the JSON files and use Google Maps or Bing Maps or whatever, but that doesn't feel like a good solution because you just end up looking like Bing's covid tracker which isn't very exciting.

What problems are you foreseeing?
 
> 4.) On the graphs, should we add all the lines into one graphs and let people choose to their hearts content, or should we break into different graphs. The former is cleaner, but it does introduce issues with laying the burden on the user, and some lines need to be different scales (left vs. right axis, some people want to see 3-d average etc). we might be are solving too many problems at one go.

I know I tried pitching you before on one graph to rule them all but I think you were right to push back. I still believe strongly we want one graph *component* to rule them all, but that doesn't get in the way of curating useful graphs for the user like you've been doing and that's good. In these screenshots I've been doing one graph (well, now two graphs) to rule them all because I am lazy :)

3-d average is super easy, assuming you're okay with it showing up as its own series like trend does (which might even be a good thing considering how many people ask what the 3-d line is!) I think biaxial is easy but haven't tried. I guess it might end up weird if we have biaxial and then people turn off the line that uses it, but it should be fine.

**Comment by aschleck** [comment]
Your proposed button and priorities sound good to me!

For search I was thinking of using the search bar + app bar example MUI has. Probably right aligned. What do you think?

image

Some more priorities:
* P0 ReCharts's log scale is super buggy for whatever reason. Half the time it just refuses to render any data. Similarly the days to double graph has data for Beijing but ReCharts isn't rendering it, even in linear (I think because some data points are infinite.)
* P0 sort the data tables
* P0 pull in the comments and the footer
* P0 figure out if we really want the thing to say "Earth", it feels dorky but I didn't know what else to put. "World" doesn't sound right to me.
* P? pull in the social media icons (do you have any sense of how often people share using these?)
* P? do we care about per capita in the table?
* P? I personally love the days to double column in the US data tables and I am missing that as well. It's gnarly because it would mean instantiating a bunch of the data right now, so maybe there's some work for me to do on improving the general situation there

**Comment by aschleck** [comment]
* P? decide if we want to show these numbers, and if so how

image

**Comment by xunhuang** [comment]
Pardon the brevity (in bed when iPhone)

- happy to try the appbar.
- Snorri did something with the d3-scale with the log thing to avoid the
log 0 issue. In graphnewcase.js
-can drop the social media button, I don’t think it gets clicked on a lot.
Didn’t measure it though. If it gets clicked on a lot we would have more
users.
- yes people love the per capita, they use that for comparison.
- I can generate the 2x # and put into the world data.json

April Schleck <notifications@github.com>於 2020年5月4日 週一，上午12:01寫道：

**Comment by aschleck** [comment]
Do we have the population numbers somewhere to support per capita in ROW? I am not seeing them, but wouldn't be surprised if I just missed it.

**Comment by xunhuang** [comment]
currently we don't. I'm going through the countries one by one to fix all the names. wondering if at someopoint we should should assume country codes. 
Also, there are populations of the regions/states in the country too, if we want to be complete.

**Comment by aschleck** [comment]
Regions/states is probably a good opportunity for SPARQL, something like this: https://query.wikidata.org/#SELECT%20distinct%20%3Fcode%20%3Ftype%20%3Farea%20%3FareaLabel%20%3Ftotal%0A%0AWHERE%20%7B%0A%20%20%3Farea%20wdt%3AP1082%20%3Ftotal.%0A%20%20%7B%3Farea%20wdt%3AP297%20%3Fcode.%20%3Farea%20wdt%3AP31%2Fwdt%3AP279%2a%20wd%3AQ6256.%20BIND%28%22country%22%20as%20%3Ftype%29%7D%0A%20%20%20%20%20%20UNION%20%7B%3Farea%20wdt%3AP300%20%3Fcode.%20%3Farea%20wdt%3AP31%2Fwdt%3AP279%2a%20wd%3AQ10864048.%20BIND%28%22region%22%20as%20%3Ftype%29%7D.%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22.%20%7D%0A%7D%0A maybe?

At least countries, US states, places in China like "Anhui" and "Beijing" show up in that query, and places in GB like "Wales". I also pulled ISO 3166 country codes and region codes into it.

It would probably be good to normalize data onto the standard ISO 3166 codes as it would give us a consistent key. Though I'm not quite sure how to map "Mainland China" onto the CN country code since aiui "Mainland China" doesn't include Hong Kong but CN does. Maybe it doesn't matter.

**Comment by aschleck** [comment]
It occurs to me that IDs would also be better for our URLs than using the direct names, so we can rename the names without breaking ads and bookmarks.

**Comment by xunhuang** [comment]
that sparkQL is amazing. I'm 80% through the clean up off the names. will
power through that first.

**Comment by xunhuang** [comment]
[countries.txt](https://github.com/xunhuang/covid-19/files/4577379/countries.txt)
this is the newly compiled country list (no data), please eyeball it.

**Comment by aschleck** [comment]
This looks great! I only noticed a few things

There's still South with Korea as a province
Taiwan has an asterisk
Congo shows up twice as two cities (I think?)
Might be good to make US instead United States (or maybe even longer of America) to be in line with the other country names

**Comment by xunhuang** [comment]
Fixed the south Korea, Taiwan and US(to United States). Congo was listed as two by JHU, probably some dynamics that we don't know how so let's keep that (probably things like HK/Macau/Taiwan relating to China).

**Comment by aschleck** [comment]
New data looks great! But I think South Korea is now "Korea South".

I made the table sortable, will investigate Snorri's work on the log scale.

**Comment by tumbleshack** [comment]
> Fixed the south Korea, Taiwan and US(to United States). Congo was listed as two by JHU, probably some dynamics that we don't know how so let's keep that (probably things like HK/Macau/Taiwan relating to China).

There's two countries with the name Congo that have confusingly similar full names: [DROC](https://en.wikipedia.org/wiki/Democratic_Republic_of_the_Congo) and [Republic of the Congo](https://en.wikipedia.org/wiki/Republic_of_the_Congo). They're often referred to by their largest cities: Kinsasha and Brazzaville, respectively.

**Comment by xunhuang** [comment]
> There's two countries with the name Congo that have confusingly similar full names: [DROC](https://en.wikipedia.org/wiki/Democratic_Republic_of_the_Congo) and [Republic of the Congo](https://en.wikipedia.org/wiki/Republic_of_the_Congo). They're often referred to by their largest cities: Kinsasha and Brazzaville, respectively.

I will make a node for Congo, then underneath it the two cities. 

Also, @aschleck , I played with sqarql last night, pretty cool stuff, and I added in the long/lat. I'm about to switch the name to code, ok with that?

**Comment by aschleck** [comment]
Super excited about getting the IDs! Yes please. I didn't even think about lat/lng, that's a fantastic idea. I think I will try restructuring the data model to make fetching data and processing it lazily easier, do you think it's worth breaking up WorldData yet? I realize submitting this PR, even if we never render the data, will blow up the bundle size and degrade loading times. I'm thinking about adding a script to shard WorldData into loadable pieces, if you don't mind yet another pipeline script.

Also this PR seems to be getting long and I've made some tweaks to stuff in the main pages (social media icons, the footer) so I'm starting to get nervous about merge conflicts. Do you think I should break those pieces into separate PRs or should we just submit this (without linking from the main page) and then keep iterating in future PRs?

**Comment by xunhuang** [comment]
Hi April,
1) I just checked in the world data with the country/region codes. Note
that US data are there just so I can summarize the data for the world,
don't navigate into that.
2) I think you should check in the pile of PR without linking in the
navigation, otherwise, the conflicts becomes unmanageable.

As long as the existing US don't break, I don't care all that much. :)

**Pull request merged**
