### PR TITLE
Replace USCountyInfo with a data access layer and use it everywhere

### PR DESCRIPTION
**Pull request by aschleck**
I think this is a good change but curious on your perspective. It opens up the door for expanding to other countries, since at least it adds a concept of country (though with very US specific terminology.) I think I should probably have made all the accessors getter function calls (so that if the object unexpectedly is the wrong type or something the access will fail, rather than silently returning undefined), but maybe that's best left for another day.

The changes in App.js allow loading a specific county, state, or US page even if geoip is slow or fails. I think a nice medium term direction here might be to move towards fetching the JSON files asynchronously, which should mean the size of the initial JS bundle being smaller and lead to a faster page load (at least for the splash screen.) Especially if you do add non-US data, we're going to want to keep the download size as reasonable as possible. I think this approach aligns with that direction pretty reasonably.

I've tested everything I can think of except for hospital data, which doesn't load anything on my machine since I don't have access to the Firebase project and my dummy Firebase project has no hospital data. I have no idea how to set that up...

### CODE REVIEW

**Comment by xunhuang** [comment]
this code is insanely beautiful! thank you for erasing my sins. please resolve the conflicts and I will merge, test and push asap before more changes from others come in. Thank you!

**Comment by xunhuang** [comment]
Very impressed that you read through the intent of my crappy code and just did the entire refactoring. It must be clear to you that I wasn't really a react programmer, just do it as a hobby. I'm very grateful that you did this work for us without any hint of complaint, most importantly I learned a lot from you code. omg, finally **_classes_**. :) i couldn't believe we survived so long without. :p  It was embarrassing, but thank you!

**Comment by aschleck** [comment]
Aww thank you! This is a fun project to contribute to (actually my first time using React), thank you for building this and open sourcing it. I think you made the right choice when you prioritized getting code out and launching, rather than spinning in circles trying to make the perfect thing (which is what I often find myself doing...)

**Comment by xunhuang** [comment]
push to master. I will test tonight and if I don't find any obvious problem I'll deploy to prod. Thanks again!

**Comment by xunhuang** [comment]
the only problem I found was the state population seems off. (I already pushed to prod).

**Comment by xunhuang** [comment]
found it: 
-      this.population_ = parseInt(data['Population2010'].replace(',', ''));
+      this.population_ = parseInt(data['Population2010'].replace(/,/g, ''));

**Comment by aschleck** [comment]
Oops sorry about that! Thank you for finding and fixing that.

**Pull request merged**
