### PR TITLE
Add maps of counties and zipcodes of the United States organized by state

### PR DESCRIPTION
**Pull request by aschleck**
These are unstyled, with the assumption that the CSS of the surrounding page will set them appropriately (probably fill: none, stroke: something, stroke-width: something else)

### CODE REVIEW

**Comment by aschleck** [comment]
Note that in these files the FIPS county ID is not prefixed with the FIPS state

**Comment by xunhuang** [comment]
hey April, can I ask you make a change, for the statefips code, can you please add the full 5 digit code instead of truncating it? the reason some fips code are not necessary the "SSCCC" format, believe it or not. JHU stared using "90006" --> Unassigned California. not sure whether US territories are all uniformed either. so let's keep the full state fips code. 
Thanks!

(this had been a source of bugs in the backend data pipeline.)

**Comment by aschleck** [comment]
Sure, is this better?

**Comment by xunhuang** [comment]
looks great! thanks for adding the generator also!

**Pull request merged**
