### PR TITLE
Lots of changes to the world stuff

### PR DESCRIPTION
**Pull request by aschleck**
Fix missing UK data (sorry for aggressive change, I tried to fix the old script for a few hours but couldn't figure it out...) and add percent change and days 2x to the tables. Changed graph to show 3-day average. Also made loading much faster.

### CODE REVIEW

**Comment by aschleck** [comment]
This also fixes stuff  like "Lackland, TX" showing up as a state in the US data.

**Comment by xunhuang** [comment]
Is there any non-aggressive change from April? LOL...  :)

**Comment by xunhuang** [comment]
just so you know. I really enjoy reading your code!

**Comment by aschleck** [comment]
Aww thank you! I'm glad to hear that.

I'm starting to feel bad about DataSeries.js but it does a lot so I guess it's not a surprise it's complicated... Safety on all the [0] and [1]s in there is one more reason to adopt TypeScript in your next project :P

**Pull request merged**
