### PR TITLE
Create footer for github, fb, data, etc.

### PR DESCRIPTION
**Pull request by tumbleshack**
As per discussion in #3 , creating footer to contain:

1. Link to Github + FB working group
2. Term of service (disclaimer on data)
3. FAQ
4. Data Credits
5. Credits for people that contributed to this project
6. Data download links.

### CODE REVIEW

**Comment by tumbleshack** [comment]
### Read before landing

To get the Google Sheet pull working, the owner of the spreadsheet must:
- **Step 0**: Make sure the document is available to the public
- **Step 1**: Head over to [Google API Console](https://console.developers.google.com/).
- **Step 2**: Create a new Project [here](https://console.developers.google.com/projectcreate). Use any project name that makes sense to you.
- **Step 3**: Click on `Enable APIs and Services` and search for `Google Sheets`. `Google Sheets API` will show up as the sole result. Click on it.
- **Step 4**: Enable the API by click `Enable`.
- **Step 5**: Once the API is enabled, you'll see `Credentials` on the left sidebar. Click on it. Then, click on `Create Credentials` > `API Key` (you may have to refresh for this option to become visible).
- **Step 6**: You will now see a screen that says `API key created` with the API key. This is your API key.
- **Step 7**: Obtain the DOC ID from the URL of the Google Sheet. For example: `https://docs.google.com/spreadsheets/d/[THIS-IS-THE-DOC-ID]/`
- **Step 8**: Create a `.env` file in the root of the project with following contents:
```
REACT_APP_GOOGLE_SHEETS_API_KEY=[YOUR-API-KEY]
REACT_APP_GOOGLE_SHEETS_DOC_ID=[YOUR-DOC-ID]
```

Note that:

> This version of the Google Sheets API has a limit of 500 requests per 100 seconds per project, and 100 requests per 100 seconds per user. Limits for reads and writes are tracked separately. There is no daily usage limit.

These instructions come from the [package's readme](https://github.com/athersharif/metis/blob/master/README.md)

**Comment by xunhuang** [comment]
I think you misunderstood my point of the google sheet. I was going to pull the sheet from the build process so it's bundled in instead of having each page load to fetch from the googlesheet.

it is here now website/src/data/contributors.json 

sorry for the unclear communciation. 

data credit is at : website/src/graphs/DataCredit.js

Also, can you get your pull request into a state where squash and merge? currently its show as work in progress. 

image

Thanks for all your effort!

**Comment by tumbleshack** [comment]
Haha, that does make much more sense! Thanks. I'll change that

**Comment by tumbleshack** [comment]
You should be able to review it now.

**Comment by xunhuang** [comment]
looks good over all, can you please make the following change? 

image
can you please the link show the popup for this website/src/data/contributors.json instead?

**Comment by xunhuang** [comment]
you probably need to rebase to see this file

image

**Comment by tumbleshack** [comment]
Okay, not sure what's going one with this PR. Gonna close it and re-open

**Pull request closed without merging**
