### PR TITLE
Footer

### PR DESCRIPTION
**Pull request by tumbleshack**

### CODE REVIEW

**Comment by xunhuang** [comment]
Thanks for the feedback. can you please 

1) create a separate Pull request for this? the flow that I have seen worked well is create a pull request for each change. it's easier to manage over time as we don't have to deal with stacking too many changes together. 

2) for the popup, I was more thinking about this one: https://codesandbox.io/s/yiwhw

**Comment by tumbleshack** [comment]
> Thanks for the feedback. can you please
> 
> 1. create a separate Pull request for this? the flow that I have seen worked well is create a pull request for each change. it's easier to manage over time as we don't have to deal with stacking too many changes together.
> 2. for the popup, I was more thinking about this one: https://codesandbox.io/s/yiwhw

1. yeah... that's what I expected this to do. Not sure why the old commits are included... I believe I need to rebase. 
2. Ah! Okay. I can work on that. Would you like that type of popup for the contributors' credit as well?

**Comment by xunhuang** [comment]
> Would you like that type of popup for the contributors' credit as well?
 Yes I do.  We will have more real estate and control to work with. Thanks!

**Comment by tumbleshack** [comment]
@xunhuang , I cannot for the life of me figure out how to get rid of that huge stack of commits. I've been struggling with this all afternoon. Every time that I make a PR, they're all there. Do you have any tips?

**Comment by xunhuang** [comment]
https://stackoverflow.com/questions/14635672/rebase-a-single-git-commit

**Comment by xunhuang** [comment]
I just tried it,

git checkout master
git cherry-pick <commit ID of XX>

this worked. Replace "master" with whatever branch you want to be in.

**Comment by tumbleshack** [comment]
I created a new branch, cherry-picked in the commit I wanted, pushed it to my origin, then tried to open a PR merging my new branch into your master, and it brought the stack of 27 commits along with it

**Comment by xunhuang** [comment]
probably your new branch was off your old branch. You should pull from
master, that should have non your changes. Create a branch off that
(master), and then cherrypick your change into that new branch, and create
PR. delete your old branch as quickly as possible as it's already merged.

**Comment by tumbleshack** [comment]
I think the problem is in `master`. I guess git thinks that all those commits are not yet part of 'master'? I did the following:

1. delete my broken feature branch
2. checkout `master`; fetch `upstream` (your repo) 
3. merge `upstream/master` and push to `origin` (my fork)
4. Create a new feature branch off of `master`
5. Check out the new branch, make some changes, commit them
6. push the commit to a new upstream branch on `origin` (my fork)
7. Create a PR, observe that all 28 commits are

**Comment by xunhuang** [comment]
I think you didn't create a feature branch at the beginning so your master
was dirty.
I suggest that you do a git show for your last commit, save it.
Delete everything  and do a git clone again to start fresh.
manually redo your change again (from the saved git diff).

**Comment by tumbleshack** [comment]
That did the trick! Thanks for your help! I did:
```git reset --hard upstream/master  
git push origin master --force ```

**Comment by xunhuang** [comment]
happy to help. Glad you are so persistent. Once a while we all get into
something minor, feel free to ping me.

**Pull request closed without merging**
