### PR TITLE
Add a search box and a bunch of other nonsense

### PR DESCRIPTION
**Pull request by aschleck**
* search box
* highlighted the additional numbers you suggested in the top bar
* tweak the graphs into something more useful
* fixed the mobile layout

image
image

### CODE REVIEW

**Comment by xunhuang** [comment]
This is lovely. Question: do you prefer to launch as soon as we put in the
geo stuff, or do you want to make it more perfect. :)

There will always be feature catchup, not sure if we will be feature
In-parity. Examples:

- Maps
- projection data.
- date sliders for maps

Really up to you. I’d be supportive of what you decide.

April Schleck <notifications@github.com>於 2020年5月8日 週五，下午11:43寫道：

**Comment by aschleck** [comment]
Ahhhh too much responsibility :)

I guess launching earlier is better than launching later. I have 0 motivation to touch maps, so definitely happy to not wait for that. I do have an aspirational goal to enable comparing places on the same graph, but that might take me a long time so waiting for it would probably be a mistake.

By the way I looked around for geo location stuff, have you tried https://ip-api.com/? No idea if it's good, but it's apparently completely free for non-profit. I don't have the API keys for the geo IPs and some of the stuff makes me nervous (API key #1, API key #2, API key #3...) and makes me want to not touch it. So not sure how much work I can do on integrating that stuff. But the good/bad news with country data is it's really rare to have anything other than country level, so just taking the country code from ipdata or ip-api or whatever is probably perfect. I was planning on putting a crosshair icon (equivalent to "Find My Location") into the right side of the search box at some point, but that doesn't seem like much of a blocker.

Projections would be fun and I did some thinking about how to support the envelope in the UI. I don't really want to write the code to compute them though (I guess that would go into world_data_gen.js?) I think if you or someone else wanted to tackle computing them it'd be worth waiting for it, but otherwise I feel pretty meh.

Other things missing relative the main site:
- Last update time: this seems like it would be nice but I don't understand how the data is incrementally generated so I probably wont do this
- Graph date slider: do you have a preference on that vs https://recharts.org/en-US/examples/HighlightAndZoomLineChart? I like the highlight and zoom, but if you don't then that's fine
- Comments: honestly I am procrastinating on this because the toggle between Disqus and FB Comments makes me sad... But I will get over it and add it.
- Obviously stuff like testing and hospitalization data
- Per capita death metrics in the table. I have a lot of space on the desktop view where it could easily fit, but I have no space on the mobile view. I'm not sure whether to add another tab, just let it be missing, or let it scroll. I think I want to let it scroll. Doesn't seem like a launch blocker.
- Biaxial graphs: I honestly find these really hard to read, I could definitely make the code support this but I just sort of feel like... why?
- Growth graph (I already have doubling.) I never understood the growth graph, so hesitant to add it, but it could be done I guess. Just requires writing the code, I probably wont personally do it
- County level lat/lngs/population: obviously not a blocker since we're carving out the US but would be nice to get these into world_data_gen
- Resources and news: not sure how important this is to you

Anyway yeah, I guess let's do the geo stuff and see how it goes?

**Comment by aschleck** [comment]
Oh of course metros are missing too. But we have so little detailed country data that there's no point in metros outside the US

And links to public health departments are missing

**Comment by xunhuang** [comment]
hey, lets move this conversation to a github issue instead. the PR keeps
closing. :)

**Comment by xunhuang** [comment]
https://github.com/xunhuang/covid-19/issues/121

**Pull request merged**
